### ISSUE TITLE
Can a menu option be added instead of the on-screen save/load state buttons.

### ISSUE THREAD

**Issue by MrThista** [tytydraco/Ludere#3]
The bottons are too easy to tap when playing which may cause you to load a state and loose progress.

In addition a controller shortcut would be beneficial for controller users.

**Comment by tytydraco** [comment]
I can consider an on-screen menu but I'm not sure if I want to add any extra layers of abstraction. Maybe I can reposition the state buttons instead.

As for the controller, there is already a config for shortcuts: `config_modifier_keys`:

* Select+L1: Load
* Select+R1: Save
* Start+L1: Mute
* Start+R1: Fast Forward

**Comment by MrThista** [comment]
Ok great, could there be a confirmation button confirming that you want to load/save?

**Comment by tytydraco** [comment]
I'd prefer not to do that because in games like Mega Man where you're using it a lot (unless you are a Mega Man god), it's annoying to click confirm every single time. I have also never clicked load state / save state by accident. I guess if this is really a problem, I can reposition the buttons to the top of the screen where you wouldn't click it with your palm accidentally. Or you can disable the onscreen save / load buttons in the config and only use a controller for clicking those.

**Comment by MrThista** [comment]
Haha good point. I normally disable them. There's something nostalgic about using the traditional saves which I like. But annoying when the game only allows you to save at certain points. But using the save and load on app exit and app open would normally be fine.

**Comment by tytydraco** [comment]
@MrThista I added an on-screen menu, pull the latest commits, and update your config to the new template. Hope you like it!
